version: '3.7'

services:

  postgres:
    image: postgres:12-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  datasetAccess:
    build: .
    image: dataset-access:dev
    ports:
      - 8989:8080
    environment:
      PGPOOL_CONNECT_dash_OPTIONS_HOST: postgres
      PGPOOL_CONNECT_dash_OPTIONS_PORT: 5432
      FLYWAY_URL: jdbc:postgresql://postgres:5432/rdc
    depends_on:
      - postgres
