webserver:
  port: 10100
  host: "0.0.0.0"
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  port: 10108

pgpool:
  connect-options:
    port: 15432
    host: localhost
    database: rdc
    user: rdc
    password: rdc
  pool-options:
    max-size: 5

flyway:
  url: jdbc:postgresql://localhost:15432/rdc
  user: rdc
  password: rdc

init:
  db-connectivity-attempts: 3

health:
  readiness:
    idle-timeout: 2000
