webserver:
  port: 8080
  host: "0.0.0.0"

grpcserver:
  port: 7070

pgpool:
  connect-options:
    port: 15432
    host: localhost
    database: rdc
    user: rdc
    password: rdc
  pool-options:
    max-size: 5

flyway:
  url: jdbc:postgresql://localhost:15432/rdc
  user: rdc
  password: rdc

init:
  db-connectivity-attempts: 3

health:
  readiness:
    idle-timeout: 2000
