endpoints:
  prometheus:
    enabled: true
    sensitive: false
micronaut:
  application:
    name: dataset-access
  metrics:
    enabled: true
    sensitive: false
datasources:
  datasetUserAccess:
    url: jdbc:postgresql://localhost:15432/rdc
    username: rdc
    password: rdc
    driverClassName: org.postgresql.Driver
    connectionTimeout: 2000 # Hikari, maximum number of milliseconds that a client will wait for a connection from the pool
    queryTimeout: 2000ms
