endpoints:
  prometheus:
    enabled: true
    sensitive: false
micronaut:
  application:
    name: dataset-access
  metrics:
    enabled: true
    sensitive: false
postgres:
  reactive:
    client:
      port: 15432
      host: localhost
      database: rdc
      user: rdc
      password: rdc
      maxSize: 5
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1.0
    sender:
      agentHost: localhost
      agentPort: 5775
    reporter:
      flushInterval: 2000
      maxQueueSize: 200