endpoints:
  prometheus:
    enabled: true
    sensitive: false
micronaut:
  application:
    name: dataset-access
  metrics:
    enabled: true
    sensitive: false
postgres:
  reactive:
    client:
      port: 15432
      host: localhost
      database: rdc
      user: rdc
      password: rdc
      maxSize: 5
