webserver:
  port: 10100
  host: "0.0.0.0"
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:25432/user_access"
    username: "user_access"
    password: "user_access"
  statements:
    ping: "DO 0"

flyway:
  url: jdbc:postgresql://localhost:25432/user_access
  user: user_access
  password: user_access

init:
  db-connectivity-attempts: 120

health:
  readiness:
    idle-timeout: 2000

tracing:
  enabled: true
  service: user-access
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false
